### ISSUE TITLE
Great weapons (d10) have a large average damage

### ISSUE THREAD

**Issue by Lambosaurus** [Lambosaurus/hives-and-torches#10]
Because I insisted on 2x weapon dice, the damage potential of great weapons in the first few levels seems too high. 

I am considering putting them behind a feat. 2d10 damage is fine if you invest.

They have poor crit chance, so perhaps great weapons have a big crit option?

**Comment by Hoppelite** [comment]
I don't think it is that bad, I think having to use 2-hands should be a detriment though without proper feats. You could possibly 
just have shields be valuable, so not using one is dangerous unless they get a feat to use their great weapon more defensive.

**Comment by Lambosaurus** [comment]
Yes, I think we definitely need some class stuff/feats to restrict who can wield what. Just not sure how to implement it without it being a huge feat soak.

**Comment by LouderthanThunder** [comment]
Suck it up lil bitch
